databases:
  # Managed Cloud PostgreSQL Database
  - name: hotel-postgres-db
    databaseName: hotel
    user: postgres
    plan: free
    region: oregon

services:
  # Spring Boot REST API
  - type: web
    name: hotel-bed-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: hotel-postgres-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: hotel-postgres-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: hotel-postgres-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: hotel-postgres-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hotel-postgres-db
          property: password
      - key: MAIL_USERNAME
        value: msdkalaikalai@gmail.com
      - key: MAIL_PASSWORD
        sync: false

  # React + Vite Static Frontend
  - type: static
    name: hotel-bed-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
